/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithMeRouteImport } from './routes/work-with-me'
import { Route as PrivatePaymentRouteImport } from './routes/private-payment'
import { Route as OrganizationsFigmaRouteImport } from './routes/organizations-figma'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactV2RouteImport } from './routes/contact-v2'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutV2RouteImport } from './routes/about-v2'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkWithMeRoute = WorkWithMeRouteImport.update({
  id: '/work-with-me',
  path: '/work-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatePaymentRoute = PrivatePaymentRouteImport.update({
  id: '/private-payment',
  path: '/private-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsFigmaRoute = OrganizationsFigmaRouteImport.update({
  id: '/organizations-figma',
  path: '/organizations-figma',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactV2Route = ContactV2RouteImport.update({
  id: '/contact-v2',
  path: '/contact-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutV2Route = AboutV2RouteImport.update({
  id: '/about-v2',
  path: '/about-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-v2': typeof AboutV2Route
  '/contact': typeof ContactRoute
  '/contact-v2': typeof ContactV2Route
  '/insights': typeof InsightsRoute
  '/organizations': typeof OrganizationsRoute
  '/organizations-figma': typeof OrganizationsFigmaRoute
  '/private-payment': typeof PrivatePaymentRoute
  '/work-with-me': typeof WorkWithMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-v2': typeof AboutV2Route
  '/contact': typeof ContactRoute
  '/contact-v2': typeof ContactV2Route
  '/insights': typeof InsightsRoute
  '/organizations': typeof OrganizationsRoute
  '/organizations-figma': typeof OrganizationsFigmaRoute
  '/private-payment': typeof PrivatePaymentRoute
  '/work-with-me': typeof WorkWithMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-v2': typeof AboutV2Route
  '/contact': typeof ContactRoute
  '/contact-v2': typeof ContactV2Route
  '/insights': typeof InsightsRoute
  '/organizations': typeof OrganizationsRoute
  '/organizations-figma': typeof OrganizationsFigmaRoute
  '/private-payment': typeof PrivatePaymentRoute
  '/work-with-me': typeof WorkWithMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-v2'
    | '/contact'
    | '/contact-v2'
    | '/insights'
    | '/organizations'
    | '/organizations-figma'
    | '/private-payment'
    | '/work-with-me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-v2'
    | '/contact'
    | '/contact-v2'
    | '/insights'
    | '/organizations'
    | '/organizations-figma'
    | '/private-payment'
    | '/work-with-me'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-v2'
    | '/contact'
    | '/contact-v2'
    | '/insights'
    | '/organizations'
    | '/organizations-figma'
    | '/private-payment'
    | '/work-with-me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutV2Route: typeof AboutV2Route
  ContactRoute: typeof ContactRoute
  ContactV2Route: typeof ContactV2Route
  InsightsRoute: typeof InsightsRoute
  OrganizationsRoute: typeof OrganizationsRoute
  OrganizationsFigmaRoute: typeof OrganizationsFigmaRoute
  PrivatePaymentRoute: typeof PrivatePaymentRoute
  WorkWithMeRoute: typeof WorkWithMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-me': {
      id: '/work-with-me'
      path: '/work-with-me'
      fullPath: '/work-with-me'
      preLoaderRoute: typeof WorkWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-payment': {
      id: '/private-payment'
      path: '/private-payment'
      fullPath: '/private-payment'
      preLoaderRoute: typeof PrivatePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations-figma': {
      id: '/organizations-figma'
      path: '/organizations-figma'
      fullPath: '/organizations-figma'
      preLoaderRoute: typeof OrganizationsFigmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-v2': {
      id: '/contact-v2'
      path: '/contact-v2'
      fullPath: '/contact-v2'
      preLoaderRoute: typeof ContactV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-v2': {
      id: '/about-v2'
      path: '/about-v2'
      fullPath: '/about-v2'
      preLoaderRoute: typeof AboutV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutV2Route: AboutV2Route,
  ContactRoute: ContactRoute,
  ContactV2Route: ContactV2Route,
  InsightsRoute: InsightsRoute,
  OrganizationsRoute: OrganizationsRoute,
  OrganizationsFigmaRoute: OrganizationsFigmaRoute,
  PrivatePaymentRoute: PrivatePaymentRoute,
  WorkWithMeRoute: WorkWithMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
